name: CI/CD

on:
  push:
    branches: [build_and_deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x' #Version of node.js

      - name: Install dependencies
        run: |
          cd parcial2/frontend
          npm install
          cd ../backend
          npm install
      
      - name: Build
        run: |
          cd parcial2/backend
          npm run build
          cd ../frontend
          npm run build
      
    