# FILEPATH: /c:/Users/JULIAN DAVID/Desktop/Proyecto_Informatico/.github/workflows/backend.yml

name: Build and deploy backend to Azure Web App - taskapp2023

on:
  push:
    branches:
      - dev
      - try_build_and_deploy
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Nest.js dependencies and build backend
        run: |
          cd parcial2/backend
          npm install
          npm run build 
        env:
          CI: true
          
      - name: Archive backend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifacts
          path: parcial2/backend/dist
  deploy_backend:
    needs: build_backend
    runs-on: ubuntu-latest
    steps:
      - name: Download backend artifacts
        uses: actions/download-artifact@v3
        with:
          name: backend-artifacts
          path: parcial2/backend/dist

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: your-web-app-name
          slot-name: your-slot-name # Optional, if deploying to a specific slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: parcial2/backend/dist
