# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - taskapp2023

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Nest.js dependencies and build backend
        run: |
          cd parcial2/backend
          npm install
          npm run build 
          
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip


  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.yarnpkg.com'

      - name: Install React dependencies and build frontend
        run: |
          cd parcial2/frontend
          yarn install
          yarn build
        env:
          CI: true
          
      - name: Archive frontend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifacts
          path: frontend/build

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_backend
 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'taskapp2023'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CFB62C978C304B3FA07C228D79927B29 }}
          package: .
        env:
          AZURE_CORE_COLLECT_TELEMETRY: 'no'
          
  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-artifacts
          path: frontend-artifacts

      - name: Deploy React to Azure Storage Static Website (Frontend)
        uses: Azure/static-web-apps-deploy@v1
        with:
          app-location: 'frontend'
          output-location: 'frontend/build'
          index-document: 'index.html'
